steps:
  - name: 'gcr.io/$PROJECT_ID/packer'
    args:
      - build
      - -var
      - image_name=hello-v1
      - -var
      - project_id=jafudi-1558282200187
      - -var
      - image_family=hello-world
      - -var
      - image_zone=us-east1-b
      - packer.json