steps:
  - name: 'gcr.io/$PROJECT_ID/packer'
    env:
      - PACKER_LOG=1
    args:
      - build
      - -debug
      - -var
      - image_name=traction-$SHORT_SHA
      - -var
      - project_id=jafudi-1558282200187
      - -var
      - image_family=jafudi-traction
      - -var
      - image_zone=europe-west3-b
      - -var
      - headless=true
      - packer-desktop/ubuntu/pack-lubuntu.json
timeout: 2400s