steps:
  - name: 'gcr.io/$PROJECT_ID/packer'
    env:
      - PACKER_LOG=1
    args:
      - build
      # https://packer.io/docs/other/debugging.html
      - -debug
      - -var
      - image_name=traction-$SHORT_SHA
      - -var
      - project_id=jafudi-1558282200187
      - -var
      - image_family=jafudi-traction
      - -var
      - image_zone=europe-west3-b
      - packer.json

  # https://cloud.google.com/sdk/gcloud/reference/compute/images/export
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - images
      - export
      - --quiet
      - --destination-uri
      - gs://jafudi/ideops-on-lubuntu-qt-64.vmdk
      - --image
      - traction-$SHORT_SHA
      - --image-project
      - jafudi-1558282200187
      - --export-format
      - vmdk
      - --zone
      - europe-west3-b
timeout: 2400s
