steps:
  - name: 'gcr.io/$PROJECT_ID/packer'
    args:
      - build
      - -var
      - project_id=jafudi-1558282200187
      - -var
      - image_family=jafudi
      - -var
      - image_zone=europe-west3-b
      - packer.json

  # https://cloud.google.com/sdk/gcloud/reference/compute/images/export
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - images
      - export
      - --quiet
      - --destination-uri
      - gs://jafudi/ideops-on-lubuntu-64.vmdk
      - --image-family
      - jafudi
      - --image-project
      - jafudi-1558282200187
      - --export-format
      - vmdk
timeout: 2400s
