#cloud-config

users:
  - name: "${GATEWAY_USERNAME}"

timezone: "${GATEWAY_TIMEZONE}"

package_update: true
package_upgrade: false
packages:
  - docker.io
  - nano
  - iptables-persistent
  - glances

runcmd:
  - export DEBIAN_FRONTEND=noninteractive
  - rm -rf /var/log/unattended-upgrades
  - apt-get -qq purge unattended-upgrades snapd apport
  - apt-get -qq autoremove