#cloud-config

users:
  - default

# Set the system timezone
timezone: "${DESKTOP_TIMEZONE}"

package_update: true
package_upgrade: false
packages:
  - nano
  - net-tools
  - glances
  - darkstat

# locale: "${DESKTOP_LOCALE}"

mounts:
  - ["${GATEWAY_USERNAME}@${SSL_DOMAIN}:/home/${GATEWAY_USERNAME}/uploads", "/home/${DESKTOP_USERNAME}/Desktop/Uploads"]

mount_default_fields:
  - "none"
  - "none"
  - "fuse.sshfs"
  - "nofail,noauto,_netdev,IdentityFile=/home/${DESKTOP_USERNAME}/.ssh/vm_key,x-systemd.automount,x-systemd.requires=cloud-init.service,allow_other,users,idmap=user"
  - "0"
  - "0"

# https://blog.luukhendriks.eu/2019/01/25/sshfs-too-many-levels-of-symbolic-links.html
runcmd:
  - "touch /home/${DESKTOP_USERNAME}/Desktop/Uploads/can_write_as_root || echo  SSHFS mount not working yet. Try again later..."
  - export DEBIAN_FRONTEND=noninteractive
  - rm -rf /var/log/unattended-upgrades
  - apt-get -qq purge unattended-upgrades snapd apport
  - apt-get -qq autoremove
