#cloud-config

# BOOT STAGE: init-local

# BOOT STAGE: init-network
#   Module: seed_random
#   Module: bootcmd
#   Module: write-files
#   Module: growpart
#   Module: resizefs
#   Module: disk_setup
#   Module: mounts
mounts:
  - ["${GATEWAY_USERNAME}@${SSL_DOMAIN}:/home/${GATEWAY_USERNAME}/uploads", "/home/${DESKTOP_USERNAME}/Desktop/Uploads"]

mount_default_fields:
  - "none"
  - "none"
  - "fuse.sshfs"
  - "nofail,noauto,_netdev,IdentityFile=/home/${DESKTOP_USERNAME}/.ssh/vm_key,x-systemd.automount,x-systemd.requires=cloud-init.service,allow_other,users,idmap=user"
  - "0"
  - "0"
#   Module: set_hostname
#   Module: update_hostname
#   Module: update_etc_hosts
#   Module: ca-certs
#   Module: rsyslog
#   Module: users-groups
users:
  - default
#   Module: ssh

# BOOT STAGE: modules-config
#   Module: ssh-import-id
#   Module: locale
# locale: "${DESKTOP_LOCALE}"
#   Module: set-passwords
#   Module: grub-dpkg
#   Module: apt-pipelining
#   Module: apt-configure
#   Module: ntp
#   Module: timezone
timezone: "${DESKTOP_TIMEZONE}"
#   Module: disable-ec2-metadata
#   Module: runcmd
runcmd:
  - "touch /home/${DESKTOP_USERNAME}/Desktop/Uploads/can_write_as_root || echo  SSHFS mount not working yet. Try again later..."

# BOOT STAGE: modules-final
#   Module: package-update-upgrade-install
#   Module: scripts-vendor
#   Module: scripts-per-once
#   Module: scripts-per-boot
#   Module: scripts-per-instance
#   Module: scripts-user
#   Module: ssh-authkey-fingerprints
#   Module: keys-to-console
#   Module: phone-home
#   Module: final-message
#   Module: power-state-change
power_state:
  delay: now
  mode: reboot
