#cloud-config

users:
  - default

# Set the system timezone
timezone: "${DESKTOP_TIMEZONE}"

locale: "${DESKTOP_LOCALE}"

mounts:
  - ["ubuntu@${SSL_DOMAIN}:/home/ubuntu/uploads", "/home/ubuntu/Desktop/Uploads"]

mount_default_fields:
  - "none"
  - "none"
  - "fuse.sshfs"
  - "nofail,noauto,_netdev,IdentityFile=/home/ubuntu/.ssh/vm_key,x-systemd.automount,x-systemd.requires=cloud-init.service,allow_other,users,idmap=user"
  - "0"
  - "0"

# https://blog.luukhendriks.eu/2019/01/25/sshfs-too-many-levels-of-symbolic-links.html
runcmd:
    - "touch /home/ubuntu/Desktop/Uploads/can_write_as_root || echo  SSHFS mount not working yet. Try again later..."
