#cloud-config

# run commands
# default: none
# runcmd contains a list of either lists or a string
# each item will be executed in order at rc.local like level with
# output to the console
# - runcmd only runs during the first boot
# - if the item is a list, the items will be properly executed as if
#   passed to execve(3) (with the first arg as the command).
# - if the item is a string, it will be simply written to the file and
#   will be interpreted by 'sh'
#
# Note, that the list has to be proper yaml, so you have to quote
# any characters yaml would eat (':' can be problematic)
runcmd:
    - >
        sudo gitlab-runner register
        --non-interactive
        --url="https://gitlab.com/"
        --registration-token="JW6YYWLG4mTsr_-mSaz8"
        --executor="shell"
        --description="ludopy-local-shell"
        --tag-list="localhost,bash"
    - sudo gitlab-runner restart
    - sudo gitlab-runner status