#cloud-config

bootcmd:
  - mkdir -p /home/ubuntu/uploads
  - chown -R ubuntu /home/ubuntu

users:
    - default

# Set the system timezone
timezone: "${GATEWAY_TIMEZONE}"

locale: "${GATEWAY_LOCALE}"

write_files:
- content: |
    ${VM_PRIVATE_KEY}
  path: /home/ubuntu/.ssh/vm_key
  owner: root:root
  permissions: '0600'
  append: false


