#cloud-config

groups:
  - ubuntu: [root,sys]
  - cloud-users

# Add users to the system. Users are added after groups are added.
# Note: Most of these configuration options will not be honored if the user
#       already exists. Following options are the exceptions and they are
#       applicable on already-existing users:
#       - 'plain_text_passwd', 'hashed_passwd', 'lock_passwd', 'sudo',
#         'ssh_authorized_keys', 'ssh_redirect_user'.
users:
  - name: ubuntu
    sudo: "ALL=(ALL) NOPASSWD:ALL" # Set up password-less sudo for the ubuntu user

timezone: "${GATEWAY_TIMEZONE}"

package_update: true
package_upgrade: false
packages:
  - docker.io
  - nano
  - darkstat
  - iptables-persistent
  - glances

runcmd:
  - rm -rf /var/log/unattended-upgrades
  - DEBIAN_FRONTEND="noninteractive" apt-get -qq purge unattended-upgrades snapd apport
  - DEBIAN_FRONTEND="noninteractive" apt-get -qq autoremove