#cloud-config

users:
  - default

# Set the system timezone
timezone: "${GATEWAY_TIMEZONE}"

# locale: "${GATEWAY_LOCALE}"

package_update: true
package_upgrade: false
packages:
  - docker.io
  - nano
  - darkstat
  - iptables-persistent
  - glances

# runcmd only runs during the first boot
runcmd:
  - [ systemctl, enable, --now, docker ]
  - [ usermod, -aG, docker, ubuntu ]
  - [ curl, --silent, -L,
      "${DOCKER_COMPOSE_REPO}/docker-compose-$(uname -s)-$(uname -m)",
      -o, /usr/local/bin/docker-compose ]
  - [ chmod, +x, /usr/local/bin/docker-compose ]
  - [ passwd, -d, ubuntu ] # for direct SSH access from guacd_container